### PR TITLE
add python 3.8-dev to CI

### PR DESCRIPTION
**Pull request by rsokl**

### CODE REVIEW

**Comment by rsokl** [comment]
Tracking:
- https://github.com/numpy/numpy/issues/14698
- https://github.com/scipy/scipy/issues/10927

**Comment by davidmascharka** [comment]
Can this be revisited? I'm running 3.8 on my machine and have no issues.

**Comment by rsokl** [comment]
SciPy has been the blocker. Are you able to install it?

**Comment by davidmascharka** [comment]
Yep:

```
$ pip install --upgrade scipy
$ Requirement already up-to-date: scipy in /usr/lib/python3.8/site-packages (1.4.1)

$ [david@shark ~]$ ipython
Python 3.8.1 (default, Dec 21 2019, 20:57:38) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.11.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import scipy                                                                                                           

In [2]: scipy.__version__                                                                                                      
Out[2]: '1.4.1'

In [3]:  
```

**Comment by rsokl** [comment]
Oh maybe `numba` was the blocker? Attempting to re-build

**Comment by rsokl** [comment]
@davidmascharka woo! it works now!

**Pull request merged**
