### PR TITLE
Graph bug fixing

### PR DESCRIPTION
**Pull request by Anonymission**

### CODE REVIEW

**Comment by Anonymission** [comment]
I just started getting backend errors as well; they seem to be related to `python-graphviz` and not graphviz itself

```
---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
~/anaconda/lib/python3.6/site-packages/IPython/core/formatters.py in __call__(self, obj)
    334             method = get_real_method(obj, self.print_method)
    335             if method is not None:
--> 336                 return method()
    337             return None
    338         else:

~/anaconda/lib/python3.6/site-packages/graphviz/files.py in _repr_svg_(self)
    104 
    105     def _repr_svg_(self):
--> 106         return self.pipe(format='svg').decode(self._encoding)
    107 
    108     def pipe(self, format=None):

~/anaconda/lib/python3.6/site-packages/graphviz/files.py in pipe(self, format)
    123         data = text_type(self.source).encode(self._encoding)
    124 
--> 125         outs = backend.pipe(self._engine, format, data)
    126 
    127         return outs

~/anaconda/lib/python3.6/site-packages/graphviz/backend.py in pipe(engine, format, data, quiet)
    169             stderr_write_binary(errs)
    170             sys.stderr.flush()
--> 171         raise subprocess.CalledProcessError(proc.returncode, args, output=outs)
    172 
    173     return outs

CalledProcessError: Command '['dot', '-Tsvg']' died with <Signals.SIGTRAP: 5>.
```

I'll look into it more when I get a chance

**Comment by Anonymission** [comment]
I'm not quite sure what was wrong, but I was able to get around the error by installing older versions of graphviz and python-graphviz.

Specifically:
```bash
conda install graphviz=2.38.0
conda install python-graphviz=0.8.3
```

**Comment by davidmascharka** [comment]
That's super unsatisfying. If all it's doing is really calling `subprocess` then it might be easiest to just write that logic into a function; no need for the full flexibility of graphviz if we just want to use it to make a `dot` call.

**Comment by rsokl** [comment]
Oh whoa, yeah that is the error I was getting too! Did they break their library?

**Comment by Anonymission** [comment]
I think there might be compatibility issues with the current versions of `python-graphviz` (0.8.4) and `graphviz` (2.40.1). Some updates to `graphviz` were recently uploaded to [Anaconda](https://anaconda.org/anaconda/graphviz/files), which (I assume) is what @rsokl first used when testing and what I got when I updated `graphviz` today.

**Comment by Anonymission** [comment]
Looks like others are having the same problem: an [issue](https://github.com/xflr6/graphviz/issues/55) just got opened on `python-graphviz` with another error I was getting.

**Comment by xflr6** [comment]
I closed https://github.com/xflr6/graphviz/issues/55 (as you describe, this seems to be an anaconda packaging issue), please report to their repository (AFAIK this should be https://github.com/conda-forge/python-graphviz-feedstock).

**Comment by xflr6** [comment]
Not sure, if you are using https://anaconda.org/conda-forge/python-graphviz or https://anaconda.org/anaconda/python-graphviz, AFAICT the issue tracker for the former would be https://github.com/ContinuumIO/anaconda-issues

**Comment by Anonymission** [comment]
@rsokl it looks like the issue was resolved on anaconda's end (https://github.com/ContinuumIO/anaconda-issues/issues/9763)

**Comment by rsokl** [comment]
So do the standard install instructions work now?

**Comment by Anonymission** [comment]
Simply

```shell
conda install graphviz
conda install python-graphviz
```

is working for me (after updating `cairo` to the most recent version)

**Comment by rsokl** [comment]
image

Success!

**Pull request merged**
